Traceback (most recent call last):
  File "/Users/kaihuang1122/Documents/ML/Final/MLP GPT/given_err.py", line 5, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py", line 238, in <module>
    __all__.extend(core.__all__)
KeyboardInterrupt
