Traceback (most recent call last):
  File "/Users/kaihuang1122/Documents/ML/Final/MLP GPT/given_err.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__init__.py", line 83, in <module>
    from .base import clone
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py", line 6, in <module>
    import copy
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 60, in <module>
    from org.python.core import PyStringMap
  File "<frozen importlib._bootstrap>", line 1173, in _find_and_load
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 209, in _get_module_lock
KeyboardInterrupt
