Traceback (most recent call last):
  File "/Users/kaihuang1122/Documents/ML/Final/MLP GPT/given_err.py", line 6, in <module>
    from sklearn.model_selection import train_test_split
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/__init__.py", line 15, in <module>
    import logging
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/traceback.py", line 566, in <module>
    _Anchors = collections.namedtuple(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py", line 415, in namedtuple
    field_defaults = dict(reversed(list(zip(reversed(field_names),
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
