Traceback (most recent call last):
  File "/Users/kaihuang1122/Documents/ML/Final/MLP GPT/given_err.py", line 5, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py", line 157, in <module>
    from . import random
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "numpy/random/mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 42, in init numpy.random.bit_generator
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1532, in <module>
    _main_thread = _MainThread()
                   ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1403, in __init__
    Thread.__init__(self, name="MainThread", daemon=False)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 905, in __init__
    _dangling.add(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_weakrefset.py", line 85, in add
    def add(self, item):

KeyboardInterrupt
